homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 33
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include configuration/customize.yaml

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

automation: !include_dir_list configuration/automation/
device_tracker: !include_dir_list configuration/device_trackers/
camera: !include_dir_list configuration/cameras/
cover: !include_dir_list configuration/covers/
group: !include_dir_merge_named configuration/groups/
input_boolean: !include configuration/input_booleans.yaml
light: !include_dir_list configuration/lights/
media_player: !include_dir_list configuration/media_players/
script: !include_dir_merge_named configuration/scripts/
sensor: !include_dir_list configuration/sensors/
switch: !include_dir_list configuration/switches/
shell_command: !include configuration/shell_commands.yaml
zone: !include_dir_merge_list configuration/zones/


#scene: !include_dir_merge_lists configuration/scenes/


####################################################
#                                                  #
#                    Enable                        #
#                                                  #
####################################################
updater:
discovery:
history:
logbook:
frontend:
config:
sun:
logger:
recorder:
  purge_days: 7

####################################################
#                                                  #
#                    Componenets                   #
#                                                  #
####################################################


mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

zwave:
    usb_path: /dev/zwave

rfxtrx:
  device: /dev/rfxtrx

notify:
  platform: pushbullet
  api_key: !secret pushbullet_password
  name: Pushbullet

tellduslive:
  public_key: !secret telldus_public_key
  private_key: !secret telldus_private_key
  token: !secret telldus_token
  token_secret: !secret telldus_token_secret
